In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

In [19]:
df1 = pd.read_csv('X_train.csv')
df2 = pd.read_csv('y_train.csv')
df3 = pd.read_csv('X_test.csv')
df = pd.read_csv('SampleSubmission_no_output.csv')

In [20]:
X_train = df1.copy()
y_train = df2.copy()
X_test = df3.copy()
submission = df.copy()

In [5]:
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

NameError: name 'y_test' is not defined

In [13]:
predictions_lm = lm.predict(X_test)

In [34]:
predictions_lm = predictions_rf.reshape(233599)

In [36]:
predictions_lm

array([10919.37902823, 10678.03744379,  8776.75712775, ...,
       11018.21956193,  7340.5452943 ,  9186.69790443])

In [60]:
pred_lm = pd.Series(predictions_lm)

In [61]:
df_submission_lm = pd.concat([pred_lm,submission],axis=1)

In [62]:
df_submission_lm.rename({0:'Purchase'},inplace=True,axis=1)

In [63]:
df_submission_lm

Purchase  User_ID Product_ID
0       10919.379028  1000004  P00128942
1       10678.037444  1000009  P00113442
2        8776.757128  1000010  P00288442
3        9192.598818  1000010  P00145342
4       10285.015572  1000011  P00053842
...              ...      ...        ...
233594   7575.121364  1006036  P00118942
233595   8782.123534  1006036  P00254642
233596  11018.219562  1006036  P00031842
233597   7340.545294  1006037  P00124742
233598   9186.697904  1006039  P00316642

[233599 rows x 3 columns]

In [64]:
df_submission_lm.to_csv('SampleSubmission.csv',index=False)

In [ ]:
 #4693.318031081771

In [66]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

C:\Users\prana\AppData\Local\Temp\ipykernel_27496\1683572450.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)


RandomForestRegressor()

In [84]:
np.mean(cross_val_score(rf,X_train,y_train,scoring = 'neg_root_mean_squared_error'))

C:\Users\prana\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\prana\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\prana\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\prana\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y wa

-3045.2962604776844

In [69]:
predictions_rf = rf.predict(X_test)

In [70]:
predictions_rf

array([18121.82053252, 10643.04633333,  8183.16041919, ...,
       12824.61833333, 20927.835     ,  2012.91263384])

In [74]:
predictions_rf = predictions_rf.reshape(233599)

In [75]:
predictions_rf

array([18121.82053252, 10643.04633333,  8183.16041919, ...,
       12824.61833333, 20927.835     ,  2012.91263384])

In [76]:
pred_rf = pd.Series(predictions_rf)

In [79]:
df_submission_rf = pd.concat([pred_rf,submission],axis=1)

In [81]:
df_submission_rf.rename({0:'Purchase'},inplace=True,axis=1)

In [82]:
df_submission_rf

Purchase  User_ID Product_ID
0       18121.820533  1000004  P00128942
1       10643.046333  1000009  P00113442
2        8183.160419  1000010  P00288442
3        2693.556667  1000010  P00145342
4        2559.804778  1000011  P00053842
...              ...      ...        ...
233594   6804.924563  1006036  P00118942
233595   5570.391658  1006036  P00254642
233596  12824.618333  1006036  P00031842
233597  20927.835000  1006037  P00124742
233598   2012.912634  1006039  P00316642

[233599 rows x 3 columns]

In [83]:
df_submission_rf.to_csv('SampleSubmission_rf.csv',index=False)